### ISSUE TITLE
Custom Login Form update?

### ISSUE THREAD

**Issue by emrbzr** [auth0-samples/auth0-react-samples#101]
Is it possible we can get an update to custom login branch?

I am testing the branch directly on my localhost with my Auth0 creds. The only thing that works is signin/signout.

On signups i get Request to Webtask got ESOCKETTIMEDOUT(Error: Unsuccessful HTTP response)

and on social media login i get Error: invalid_request. Check the console for further details. but there is nothing on the console.

I think it is broken and needs to be updated.

Thanks.

**Comment by jimmyjames** [comment]
Closing this issue  since we've just recently made some significant changes to this sample and Quickstart, utilizing the new `auth0-spa-js` SDK. If you continue to experience this issue or any others, don't hesitate to create a new issue. Thanks!

References:
- [Updated React Quickstart](https://auth0.com/docs/quickstart/spa/react)
- [auth0-spa-js SDK](https://github.com/auth0/auth0-spa-js)
