### ISSUE TITLE
01-Login not working after browser page refresh

### ISSUE THREAD

**Issue by vincentdnl** [auth0-samples/auth0-react-samples#103]
I cloned the repo, entered my credentials in the `auth0-variables.js` file, ran `npm install` and `npm start`.
When I click on home, it asks me to login. I log in (using the Google account) and then I see the logged in home version. Everything is great except when I reload the page or close and re-open the tab.

I get this error: 

``{error: "invalid_token",  "`state` does not match."}``

then this one:

`{error: "login_required", "Login required"}`

I've tried to search a solution to this error with no success.

I did not modify the code of the example and I get the error on Firefox and Chromium on Ubuntu 18.10 (if this helps).

**Comment by bjornarhagen** [comment]
I'm having the same problem.
There is a discussion about this issue here: https://github.com/auth0/auth0.js/issues/655.
No solution yet.

**Comment by bjornarhagen** [comment]
I found a solution that worked for me.
I had to add "http://localhost:3000" in "Allowed Web Origins" in the Auth0 app settings.
I only had "http://localhost:3000/callback" in "Allowed Callback URLs".

When I refresh I still get the error, but I actually get logged in.
If I close the tab and open a new one I no longer the the error when refreshing.

Also found another discussion about this over here: https://community.auth0.com/t/invalid-token-state-does-not-match/12212/40

**Comment by techprimate-phil** [comment]
@bjornarhagen I also set up both "Allowed Web Origins" and "Allowed Callback URLs" and when I am opening `http://localhost:3000/home` in Safari the alert with `login_required` shows up everytime I am opening another tab with the same URL.
(Probably because of harder Cookie policies in Safari).

If I am opening it in Google Chrome I do get the same alert, unless I am turning of the Google Chrome setting `Block third-party cookies`.

This forum thread indicates that using Custom Domains would resolve this issue
--> https://community.auth0.com/t/checksession-always-returns-login-required-error-despite-checking-everything/12327/7
Also this documentation might be relevant: https://auth0.com/docs/cross-origin-authentication
Looks like Third-Party-Cookies might be causing this issue.
Creating a Cross Origin Authentication Page sounds unreasonable, as the browser matrix clearly states this hardly work anyways.


Can anybody verify that that custom domains are working with 01-Login example?
If it is working, shouldn't the Auth0 example work without the need or at least state that Custom Domains are required?

**Comment by sudravi** [comment]
I'm having the same problem with 01-Login unmodified (except I don't see error messages). When I refresh the browser in the logged in state, I noticed a new instance of Auth class is created. This causes expiresAt to be undefined, and isAuthenticated() to fail. Now the navbar button says Login. Should expiresAt be persisted?

**Comment by petarblazevski** [comment]
If you are using Google (or any other Social provider) you need to set up the client ID and client secret from that provider. Because out of the box Auth0 comes with development keys. In the logs, I had something like this

> You are using Auth0 development keys which are only intended for use in development and testing. This connection (google-oauth2) should be configured with your own Development Keys to enable the consent page to show your logo instead of Auth0's and to enable SSO for this connection. AUTH0 DEVELOPMENT KEYS ARE NOT RECOMMENDED FOR PRODUCTION ENVIRONMENTS. To learn more about Development Keys please refer to https://auth0.com/docs/connections/social/devkeys.

After setting up everything with Google, the problem was gone.

I hope this helps

**Comment by sudravi** [comment]
Thanks for the tip. I first ran into the problem with username/password and then again with Google auth. The first case was solved with "Silent Authentication" and the second required me to setup client ID and secret as you describe. All of this was described in a different React/Auth0 tutorial: https://auth0.com/blog/react-tutorial-building-and-securing-your-first-app/

I didn't have to persist any values like expiresAt or tokens.

**Comment by techprimate-phil** [comment]
After contacting the Auth0 Support and Sales Team, I switched to a custom domain and it resolved the issue. Google Chrome blocks third-party cookies, therefore it cannot save the authentication data into the cookie

**Comment by sudravi** [comment]
@techprimate-phil  I'm not using a custom domain and everything seems to work, no alerts. I tried both Chrome with "Block third-party cookies" turned on, as well as Safari.

**Comment by jiverson** [comment]
As @petarblazevski commented you can follow this https://auth0.com/docs/connections/social/google guide to set up a social connection for google.

**Comment by albertoperdomo** [comment]
This is a limitation of the Google developer keys provided by default in Auth0.
Use your own set of keys as described in https://github.com/auth0-samples/auth0-react-samples/issues/103#issuecomment-481012276. 

Closing.
