### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by nathan-omaorg** [auth0-samples/auth0-react-samples#128]
I am attempting to use this example as a start to implement authorisation and authentication for a new tool that I am creating. Unfortunately I am running into the error:  
"Invalid hook call. Hooks can only be called inside of the body of a function component"  

I am very new to React/Node/etc so this is probably just a failing of my understanding of how this works, but I have no idea how to work around it while still using the example given by Auth0 here.

So I am using React Components, which look like they aren't functions. Which would explain the error. However, I still need to be able to call the useAuth0() thing to show various interface changes depending on whether a user is logged in or not (e.g. a log out button if they are logged in, and vice versa).

I have implemented the react-auth0-wrapper as closely as I possibly can (I'm using TypeScript so have had to change some things, but I'm sure the error would be the same, as it seems to be breaking the React hook rules).

Here is the code that breaks: (If I remove the line `const { isAuthenticated, loginWithRedirect, logout } = useAuth0();` then it will compile and show the Hello World.

```
class Header extends React.Component {
  render(): JSX.Element {
    const { isAuthenticated, loginWithRedirect, logout } = useAuth0();
    return (
      <header className="main-header flex-row">
          <div>
              Hello world!
          </div>
      </header>
    );
  }
}

export default Header;
```

Any ideas of what I'm doing wrong or how I can adjust this example to get it to work?

Many thanks

**Comment by stevehobbsdev** [comment]
Hey @nathan-omaorg,

Yes you can only use React Hooks inside function components. These types of components are simply functions rather than classes, allowing for a simpler programmning model when it comes to using things like state. But it is a bit of a paradigm shift if you're used to using classes. Let's see how you can achieve what you want based on the example you've given.

You've got a couple of options:

**1. Covert the component to a function component**

Using function components is the most natural way to work with the Auth0 wrapper. This is what the example would look like as a function component:

```jsx
import React from "react";
import { useAuth0 } from "./react-auth0-spa";

const Header = () => {
  const { isAuthenticated, loginWithRedirect, logout } = useAuth0();

  return (
    <header className="main-header flex-row">
      <div>Hello World!</div>
    </header>
  );
};
```

This is a function called `Header` defined using arrow function syntax, which returns some JSX. You can mix and match classes and functions if you wish. So something defined as a class component can still consume this function component as normal:

```jsx
class Page extends React.Component {
    render() {
        return <Header />
    }
}
```

Given that, one pattern you could use is to break down your components so that the ones that need to interact with Auth0 could be smaller function components that are consumed by larger class components.

**2. Use the Context object directly**

The wrapper that has been written for this sample is backed by [React Context](https://reactjs.org/docs/context.html), and we export this from the wrapper module. So, if you choose, you can interact with this directly from a class component:

```jsx
import React from "react";

// Import Auth0Context instead of useAuth0
import { Auth0Context } from "./react-auth0-spa";

class Header extends React.Component {
  // Assign the context type to a static property
  static contextType = Auth0Context;

  render(): JSX.Element {
    // Destructure the values you need from this.context instead of useAuth0
    const { isAuthenticated, loginWithRedirect, logout } = this.context;

    return (
      <header className="main-header flex-row">
        <div>Hello World!
      </header>
    );
  }
}
```

I hope that helps!

**Comment by bryantson** [comment]
Definitely helpful. I wrote a blog on explaining the solution using the first method:

https://medium.com/@bryantjiminson/reactjs-how-to-handle-invalid-hook-call-warning-uncaught-error-invalid-hook-call-49ca32aa0d14
