### ISSUE TITLE
01-Login is not working on google chrome

### ISSUE THREAD

**Issue by hisashiyamaguchi** [auth0-samples/auth0-react-samples#131]
Hi,

I have deployed the app on my Amazon Linux, and now trying to login with chrome(version : 75.0.3770.100（Official Build）), but when I hit Login button upper right side its not working. Here comes my chrome logs.

Uncaught (in promise) TypeError: Cannot read property 'digest' of undefined
    at z (auth0-spa-js.production.js:570)
    at t.<anonymous> (auth0-spa-js.production.js:1050)
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.e.<computed> [as next] (runtime.js:98)
    at auth0-spa-js.production.js:66
    at new Promise (<anonymous>)
    at n (auth0-spa-js.production.js:43)
    at t.value (auth0-spa-js.production.js:1035)
    at loginWithRedirect (react-auth0-spa.js:77)

It is working on my Safari and I have deployed the app on my MacBook and trying to login on Chromse, it works fine. Please let me know the workarounds how I should do on my Amazon Linux + Google Chrome.

Best,
Hisashi Yamaguchi

**Comment by blakedietz** [comment]
@hisashiyamaguchi have you deployed your to a static host that's using https? You could be running into this problem because of [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) not being available in non secure contexts. I was running into this yesterday.

As a side note and a critique to the auth0 team, man, I was really excited about their new docs and the react hook they were providing, in comparison to previous docs it actually felt useful, but alas, I've been running into similar issues as @hisashiyamaguchi. This repo still lacks polish. Hopefully that changes as it matures.

**Comment by stevehobbsdev** [comment]
@hisashiyamaguchi As @blakedietz, you must be running the app on a secure origin (`localhost` or by using SSL) for SubtleCrypto to be available.

However, we recognise that we can do a much better job of explaining this, so I have raised this internally in an effort to improve the documentation around this.

> This repo still lacks polish. Hopefully that changes as it matures.

It's an iterative process. It's reporting issues like this that will help us get to that point, so keep them coming!
