### ISSUE TITLE
PKCE flow with Custom/Embedded UI

### ISSUE THREAD

**Issue by Sbphillips19** [auth0-samples/auth0-react-samples#139]
## Type of report
* [ ]  Bug
* [x]  Feature request
* [x]  Discussion

 ## Description
Is there a way to use this PKCE flow with an embedded/ custom UI.  I would like the user to not have to leave our custom sign in page.  The user will simply be using email and password.  Essentially, I don't want there to be a pop up to put in their information.  

I am wondering if this is possible with the new PKCE flow.  I have followed all steps to set up the new auth0-spa-js, but am unsure if there is a way to change it so that it is custom.

**Comment by luisrudge** [comment]
Not yet. Embedded login is something we want to tackle in the future but there's no ETA on this yet.

**Comment by Sbphillips19** [comment]
Hey @luisrudge, totally understandable, but I think in the meantime the old react guide should be put up/ would really benefit people trying to implement the auth0-js library rather than just the new spa library.  Not sure why it currently shows no older versions, but I have already spent a couple days trying to figure everything out and I just stumbled on a youtube video where I can see parts of the old docs.  Given that auth-js is still supported, perhaps this is still there, but digging through the whole site I can't find them.

**Comment by luisrudge** [comment]
We do have the auth0-js docs available here: https://auth0.com/docs/libraries/auth0js/v9. As for the previous react Quick Start, we revamped all the Quick Starts and moved them to the new SDK because this is our new guidance - this is what we think it's the best way to integrate Single Page Applications. If you absolutely want to check out the old sample, you can always find the point in time you want to go back and just use git to get there. Here's this repo before the update: https://github.com/auth0-samples/auth0-react-samples/tree/22b6d6a825e314be56f700dc3c34b0f825547c69/01-Login

**Comment by zhil** [comment]
@Sbphillips19 did you implement Embedded login? If yes - any chances to see your code in some kind of Gist? 

Thanks in advance, Andrew

**Comment by Sbphillips19** [comment]
@zhil sorry man, just saw this.  I'm sure by now you figured it out, but if not, or someone else needs it I put together an example a couple months ago.  https://github.com/Sbphillips19/ManualAuth0Flow

You have to install react-router-dom before running (must have changed since I made the example).  Also Auth0 changed something with CORS so it doesn't work anymore unless you set up a custom domain (paid version of auth0 (as this is just an example for myself it won't work with just npm start)).  That was a weird one where is just stopped working out of nowhere for my team and we had to upgrade and set up custom domains.
