### ISSUE TITLE
Session does not persist

### ISSUE THREAD

**Issue by yurm04** [auth0-samples/auth0-react-samples#170]
I’m trying to follow this tutorial as I create my own application https://auth0.com/docs/quickstart/spa/react/01-login

I was able to successfully log in using the GitHub connection and database email/password, but neither of these sessions is persisting between page loads. For the GitHub connection I am using my own client id (not the Auth0 development keys as seems to be the problem on similar posts). I tried with both the classic and new Universal Login features.

I also tested by cloning the tutorial project on GitHub and confirmed that the sessions are not persisting after successfully logging in.

Here is the GitHub repo for my test application. I have, for the most part, copied and pasted the relevant pieces of code from the above tutorial.
https://github.com/yurm04/chronicler-notes

Any help is appreciated!

Originally posted in the auth community forum https://community.auth0.com/t/react-spa-session-does-not-persist/34822

**Comment by leovafme** [comment]
Securing single page apps (SPAs) comes with its own set of concerns. You'll need to ensure that tokens and other sensitive data are not vulnerable to cross-site scripting and can't be read by malicious JavaScript.

We recommend using the Auth0 Single Page App SDK. The Auth0 SPA SDK handles token storage, session management, and other details for you.

see: https://auth0.com/docs/security/store-tokens#single-page-apps

**Comment by stevehobbsdev** [comment]
@yurm04 Usually we see this in the following scenarios:

* When using the classic login experience and a social connection with developement keys
* When using a browser that blocks third-party cookies (such as Brave with Shields up, or Safari)

Seeing as you mentioned that you've tried both the classic and new login experience, it's most likely the second scenario. For the silent authentication to work (what happens by default when you load the page and initialize the SDK), it relies on the `auth0` cookie being transmitted to Auth0 to rehydrate your login session. If it can't do that, it simply looks like you're logged out.

Can you tell me more about the browser you're using? Could you be using any extensions designed to block transmission of third-party cookies?

**Comment by yurm04** [comment]
@stevehobbsdev thanks for your response!  I think you might be right about some cookie blocking at play here.  My primary browser is Chrome Version 78.0.3904.108 with various extensions installed (though none that I could immediately identify that might block cookies).  When I switched to Firefox Version 71.0 the session persisted just fine, as expected.

Is there a way around this?  How do you suggest handling this case if I were to implement Auth0 in a production environment?

**Comment by stevehobbsdev** [comment]
@yurm04 Yes we are actively working on providing a solution and guidance to mitigate this. Note that this is an industry-wide issue with ITP2 and other browsers that actively block third-party cookies. The real target of technologies like Safari's ITP are tracking cookies from advertisers, but unfortunately Auth0's (and cookies from other vendors) get caught up in that net.

This won't affect you if you are authenticating the user on the same domain, so using [Custom domains](https://auth0.com/docs/custom-domains) could potentially be an option for when running in production. Note thought that **this is a paid feature**. You're affected right now because I presume your user is on `http://youapp.com` and you're authenticating them at `https://<your tenant>.auth0.com`.

Other than that, we're looking at rolling something out in the short-to-medium term but I don't have a solid ETA for you.
