### ISSUE TITLE
handleRedirectCallback() never used ?

### ISSUE THREAD

**Issue by cburkins** [auth0-samples/auth0-react-samples#174]
As best I can deduce, the function handleRedirectCallback() within react-auth0-spa.js is never used within this example.  In fact, it seems like it's actually a duplicate of the handleRedirectCallback() within auth0-spa-js (the generic javascript library).  If that's the case, why was it inserted into this tutorial ?   I'm confused.

https://github.com/auth0-samples/auth0-react-samples/blob/739b1be0913616224e6295f76bdb203022b0dd50/01-Login/src/react-auth0-spa.js#L60

**Comment by stevehobbsdev** [comment]
`handleRedirectCallback` in this sample is just a wrapper for `handleRedirectCallback` from the SDK. It takes care of setting the `loading` state correctly, plus refreshing the `isAuthenticated` and `user` states once the redirect has been processed.

You're right though that the sample appears not to use it, but it has potential to be used. The idea behind this wrapper is that it is to be extracted into another library in the future. So we put everything in here that could potentially be useful to consuming applications, so that when we do eventually extract it, it has all the pieces there.

The wrapper is subject to change though and feedback like yours is helpful to guide the implementation. Thanks for raising it!
