### ISSUE TITLE
Works well, but 2 (newbie) concerns, thanks 4 a quick look

### ISSUE THREAD

**Issue by antogh** [auth0-samples/auth0-react-samples#183]
Hi Steve,
Congrats for the well written article, I just executed your sample and it works. I understand the logic flow although I don’t understand the inner working of your components, hence I have 2 questions, sorry if they are stupid questions, I am a newbie, but I would proceed with more confidence if I know the answers.
1- Where do you store the data of already logged user? I tried to restart both browser and “npm start” and the user is quickly recognized as logged in. Do you use local browser storage? Is it safe? 
2 – I noticed the domain+clientId credentials are publicly exposed even if I create the “npm run build”, it’s easy to go with browser inside the build/static/js folder and find this info inside one of the js files. Is it safe to have this info exposed?
Thanks for the answers

**Comment by stevehobbsdev** [comment]
Hi @antogh 👋  thanks for the questions!

1) The version of the SDK used in the samples only stores data in memory. When the SDK initializes, it can make a silent call to Auth0 in the background and will log you in if you have a valid session.

However, in future versions (and this is the case if you install the beta at `@auth0/auth0-spa-js@1.7.0-beta.2` you have the option to use local storage as well. We understand there may be security concerns around what happens when you enable this option and will be publishing guidance when the beta moves into stable. However, some people are fine accepting the risks and have been doing this quite happily for some time without issue; we will leave the ultimate choice up to you.

2) The domain and client ID are not secrets and you don't need to worry about exposing them. They are already exposed through URLs and can be easily retrieved by anyone. The effect of someone retrieving those and using them is minimal as there are other protections in place (for example, you have to register in advance the `redirect_uri` value in your Auth0 dashboard, meaning that even if someone did manage to use your domain + client ID, they still can't maliciously redirect your users to another site).

I hope that answers your questions! Feel free to continue the conversation if you have more.

**Comment by antogh** [comment]
Thanks again @stevehobbsdev , you are very kind to take the time to answer. 

Point 2 is clear 👍

However about point 1, I rebooted my machine, started again the app (npm start), the default browser see me as already logged in and shows the logout button, using another browser I see the login button, so it would appear as the user info is stored in the browser.  I used the F12 and found this cookie 

![auth0 cookie](https://user-images.githubusercontent.com/8667587/75275298-9d46d580-5804-11ea-8895-2de6829d7520.png)

but it just says the user is authenticated, apparently no info about the user, is the user info retrieved from the server using the creation timestamp as key?  Sorry, I'm just curious. I tried to read the code from this line 
const isAuthenticated = await auth0FromHook.isAuthenticated();
but it's too complicated

**Comment by stevehobbsdev** [comment]
@antogh Yes, that cookie is used as an optimisation check. It indicates that we _think_ you might already be logged into Auth0. `auth0.com` also holds a cookie called `auth0` which it uses to verify that you do already have a login session on the server side, which is why you don't get prompted to put in your credentials.

> so last logged user must be stored in the browser somewhere else (in addition to the cookie)

Yes - as mentioned earlier, it's stored in memory. When the app initializes, if you inspect the network tab you will see two calls go out in the background - one to `/authorize` and another to `/token`. This is how it retrieves your details when you refresh the page. It doesn't do this if you manually remove that cookie.

Hope that makes it clearer!

**Comment by antogh** [comment]
Thanks, definitely makes sense! 
I have read also your additional article about node API authentication and next I will try ASP.NET api. 
I can't wait to write an application using Auth0 👍

**Comment by stevehobbsdev** [comment]
I'm glad! Feel free to raise any other questions as you have them, either on those samples or on [our community forums](https://community.auth0.com).

**Comment by antogh** [comment]
Steve just one more little question on your sample, shuould be easy for you. 
I am playing with customization and I was trying to force another language in the login popup. I added Italian and Spanish to my tenant settings (in Auth0 dashboard) and clicked Save

![tenant lang settings](https://user-images.githubusercontent.com/8667587/76010072-90b43280-5f12-11ea-819e-9ef648425455.png)

and then I addedd in the sources the _ui_locales_ prop like this:
```
<Auth0Provider
    domain={config.domain}
    client_id={config.clientId}
    redirect_uri={window.location.origin}
    audience={config.audience}
    onRedirectCallback={onRedirectCallback}
    ui_locales='es'
  >

```
but the login popup keep appearing in English.
Any idea on how to force another language? 
Thanks

**Comment by stevehobbsdev** [comment]
@antogh Can you let me know if you're using the "Classic" or the "New" Universal Login experience? You can see this by going to the "Universal Login" panel within your Auth0 dashboard.

**Comment by antogh** [comment]
Hi @stevehobbsdev , thanks again for your help , I solved the problem, I was using Classic but I didnt save the line of code in the universal login customization that basically propagate the ui_locale prop down to the language variable of login popup. Now it works. 

Unfortunately another thing broke :(

I created a new tenant bc I didn't like the name of the 1st one I created and it's not possible to rename. 
I moved my app in the new tenant, it works but the custom logo in the login popup is ignored (the Auth0 logo appears). It was working before in the old tenant, not anymore. 

I have created a thread in the Auth0 community 
https://community.auth0.com/t/cant-customize-logo-in-login-popup-with-my-new-tenant/39077

Do you have any idea? 

Thanks

**Comment by antogh** [comment]
@stevehobbsdev 
Custom logo also solved, it was, again, a line of code to add and save to login customization code.

**Comment by stevehobbsdev** [comment]
No problem! Glad you got it solve
