### ISSUE TITLE
Need to use passwordless

### ISSUE THREAD

**Issue by webarter** [auth0-samples/auth0-react-samples#188]
Hello!

As a part of my application, I want to allow users to enter the application for the first time using email link, and then set up their account password. 

I already have a normal authentication flow (that allows users to sign in/sign up with email and password or enter with facebook or google) working, it's great!

Now on top of that, I'm dropping the `auth0.webAuth.passwordlessStart() `into my application which successfully sends me the authentication link 
![image](https://user-images.githubusercontent.com/12608762/76005857-49c73c80-5f14-11ea-9729-6d40a8fa20cd.png)

I click on the link and get redirected to the app with such a URL:
`http://localhost:3000/#access_token=xUouoM7oxBCrtRXGP-vPY23qOwt0dWlB&scope=openid%20profile&expires_in=7200&token_type=Bearer&state=gieYoPCV8h_LsLE1gfpq~R3Ft0Sy_ARl&id_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFURTJPVUU1TXpVNU5VTXpOamc0UWtRM05ESTJSVVl3T0VWRU5UaEdNa0UwTlRFM1JETkRNUSJ9.eyJuaWNrbmFtZSI6ImtvdmFsLm1hcmZmYSIsIm5hbWUiOiJrb3ZhbC5tYXJmZmFAZ21haWwuY29tIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzdmNzU4OTkwNzdjNmNlMTc2MTJiODhmYmNkNzdmYTgwP3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGa28ucG5nIiwidXBkYXRlZF9hdCI6IjIwMjAtMDMtMDVUMTc6MDY6MjAuNzU3WiIsImlzcyI6Imh0dHBzOi8vZ2FyYWdlY2hhbXBzLmF1dGgwLmNvbS8iLCJzdWIiOiJlbWFpbHw1ZTYwZjkzZTU4MGExZDlhZjQxYWRjYWUiLCJhdWQiOiJVbWVxNjVWd2dxb1V3Q0REYWtHQjY2ZGE3RjIwZWdndyIsImlhdCI6MTU4MzQyNzk4MCwiZXhwIjoxNTgzNDYzOTgwLCJhdF9oYXNoIjoicERLZnI4R3JoTHpMdHdQMnVSb3duQSIsIm5vbmNlIjoiZGNGdFJMZ09KRlJMRVUwLnVaZ1ZHX0xvSzE3Qk40OGEifQ.EDDvr7fmYthQ2FxcOHfhIq3p3PFJYZRBPWHmowKp8IIdt-j-I6vX3x3g3JC8-7rDtlHbvPBD8DyO8a8VigKXIbRkPcix7QaDgKp5zkvL-IINYPWZUJZ7Ri01fpZPRyFtBHw6ce5Wb6IC8iTe3Cdu-Ng2kFtm2AcqrSKdF8DtUOjSnMsKIFYBN_rKpSqxLCy_CazsO2MdLU26McCU9OtSpIV_PJfLSI1Ybq6vscRP8LufzPO8VW5i_uLPn5pvTZUqHncT1-hERgvDfeENmdHjv2Qhmvxj0RlO8q84ezdvwdvXptAkPI1Z2i2bstGGPVZk8M_gjhHdV7ay2XmQLNq7lw`

As far as I understand, at that point, I need a way for the app to parse that ID token from the URL and save the information about the authorized user in the state. So that I can later access it from useAuth0()'s **user** const.

Is there a way I can process that URL with **react-auth0-spa.js**? And what should I do to achieve that? 

To be clear, I when I do a normal sign in (I write username and password), auth0 redirects back to my react app with URL `https://localhost:3000/?code=SJi1-NKBptroKMpi&state=MkdwNnp5V2NBWWdjV0ZLcFNxc0V1MnRvNHAuZlBjTHpENzViYURzVUlXbw%3D%3D` which is then parsed by  **react-auth0-spa.js** and I get access to populated **user** const  from the code. 

By **react-auth0-spa.js** I mean the one installed from this tutorial: https://auth0.com/docs/quickstart/spa/react/01-login 

How can I do the same when I land into the app with that long URL above, the one generated by passwordless authentication mode? 

Please help!

Regards,
Dmytro

**Comment by stevehobbsdev** [comment]
@webarter It looks to me like you're using both `auth0.js` for the passwordless part and `auth0-spa-js` from the tutorial in order to get the SDK wrapper that uses Hooks, is that right?

What you've got there is a callback URL for the [implicit grant](https://auth0.com/docs/api-auth/tutorials/implicit-grant), which can be parsed by Auth0.js's [parseHash](https://auth0.com/docs/libraries/auth0js/v9#extract-the-authresult-and-get-user-info) method. However, `auth0-spa-js` won't understand that you have logged in so you won't be able to retrieve any tokens or user info using that SDK - they're entirely separate.

Unfortunately we don't have any documentation or guidance around this, nor do we have support in `auth0-spa-js` to initiate the Passwordless flow. One thing you could try would be to call `getTokenSilently` on the SPA SDK _after_ you have processed the callback using `auth0.js`, as by that time you will have a session on Auth0 and it _may_ rehydrate the local session for you.

I can also recommend just using one SDK though, and if you need Passwordless support you will have to use `auth0.js`.
