### ISSUE TITLE
Auth0Client.ts:285 Uncaught (in promise) Error: Invalid state

### ISSUE THREAD

**Issue by zm3d3ni** [auth0-samples/auth0-react-samples#189]
I’m trying to add a login button to our lander page and after login I would like to redirect the user to our react application.

I added <script src="https://cdn.auth0.com/js/auth0-spa-js/1.2/auth0-spa-js.production.js"></script> to our lander page and added handler on login button click which looks like this:

```
function() {
        createAuth0Client({
            domain: 'our-domain',
            client_id: 'our-client_id'
        }).then(function(auth0) {
            auth0.loginWithRedirect({
                redirect_uri: 'our-redirect_uri',
            });
        });
    }

```
After I click a login button I’m redirected to auth0 login page I do log in and then I’m redirected to our react where we are using this react solution (https://github.com/auth0-samples/auth0-react-samples/tree/master/01-Login 1) and I’m getting this error:

```
Auth0Client.ts:285 Uncaught (in promise) Error: Invalid state
    at e.<anonymous> (Auth0Client.ts:285)
    at tslib.es6.js:99
    at Object.next (tslib.es6.js:81)
    at tslib.es6.js:73
    at new Promise (<anonymous>)
    at i (tslib.es6.js:69)
    at e.handleRedirectCallback (Auth0Client.ts:268)
    at react-auth0-spa.js:29
    at l (runtime.js:45)
    at Generator._invoke (runtime.js:271)
```

Can please someone help me solve this issue. Tnx.

**Comment by stevehobbsdev** [comment]
@zm3d3ni Can I just confirm that the lander page and the React application are on the same domain?

The login process through this SDK relies on having access to a transaction cookie that is created before redirecting to the login screen, then read again on return to your app. So that cookie must be available both before and after login.

**Comment by zm3d3ni** [comment]
@stevehobbsdev lander is on root domain and app is on a subdomain.

**Comment by stevehobbsdev** [comment]
This should work in that case. We use [`es-cookie`](https://www.npmjs.com/package/es-cookie) to manage that storage, which by default makes the cookie available to the TLD and the sub-domain.

You get this error when the SDK can't match the `state` value coming from the query string to the transaction cookie.

Are you observing that the `state` parameter appears in the querystring when Auth0 redirects you back to your app? If so, can you also see the transaction cookie from your React app, where that state value forms part of the cookie name?

**Comment by pmbaokhanh** [comment]
Hi, I have the same issue. I think it is because of URI encoding.
This is what is in my cookies: eVlYbFFaZzFtby5TUGNJYlFEcDRLeE81S0RJMndCZENVVlA0LWc5aGkwZA%3D%3D

But this is what is in the query string: eVlYbFFaZzFtby5TUGNJYlFEcDRLeE81S0RJMndCZENVVlA0LWc5aGkwZA==

Looks like the cookies is set with encoded state value, but on the redirect URL, we are not encoding it. This is causing the mismatch in my case.

**Comment by stevehobbsdev** [comment]
@pmbaokhanh I think it's [this line](https://github.com/auth0/auth0-spa-js/blob/master/src/utils.ts#L27) that's interfering. It's weird that we don't see this all the time but changing that code to be a bit more intelligent will help.

**Comment by stevehobbsdev** [comment]
@zm3d3ni @pmbaokhanh I've almost got a PR ready to go for this. However, I'm unable to reproduce what you're seeing. When I log in, I'm generating a state value that is properly encoded in the querystring and I'm getting that same encoded value back through the URL, meaning I don't get the mismatched state error.

Can I confirm with you both:

* You're using Auth0 as your IdP (as opposed to trying to authenticate with a third-party)?
* Are you using the Classic or the New login experience? (Check this in [your dashboard](https://manage.auth0.com)

**Comment by hubertokf** [comment]
I'm having the same issue.

**Comment by MEOWMEOW114** [comment]
hows the update of this issue?
it is very annoying that this issue still haven't been fixed yet this is very obvious

**Comment by stevehobbsdev** [comment]
@MEOWMEOW114 The update is that I'm still unable to reproduce the scenario here, so I'm still looking for a reproducible set of steps that I can use to verify the issue before committing changes to the repository.

**Comment by stevehobbsdev** [comment]
@jdorn That is entirely expected - if you don't redirect away or clear the URL params, then the SDK will try to validate the state again on subsequent requests, but by that time the transaction cookie has been removed. This then generates the error. [Mitigating this is demonstrated in the sample](https://github.com/auth0-samples/auth0-react-samples/blob/master/01-Login/src/react-auth0-spa.js#L4-L5).

**Comment by stevehobbsdev** [comment]
👋  we still do not have concrete steps to reproduce this problem. Reading the conversation above, this is mostly likely a tenant configuration problem rather than a problem with the SDK.

For tenant configuration, the best place to raise this is in the [Auth0 community forums](https://community.auth0.com).
If some steps can be generated that reproduce an issue with the SDK itself, the best place to raise that is on the [SDK issue tracker](https://github.com/auth0/auth0-spa-js/issues).

The [React quickstart](http://auth0.com/docs/quickstart/spa/react) and this sample have since been updated to take advantage of the new [React SDK](http://github.com/auth0/auth0-react). We'll close this for now, but please raise another issue here if there are further problems specific to this sample.

**Comment by ben-dyer** [comment]
Started encountering similar error at `src/Auth0Client.ts:415` after having added then removed an Application Login URI

**Comment by cpustejovsky** [comment]
> @jdorn That is entirely expected - if you don't redirect away or clear the URL params, then the SDK will try to validate the state again on subsequent requests, but by that time the transaction cookie has been removed. This then generates the error. [Mitigating this is demonstrated in the sample](https://github.com/auth0-samples/auth0-react-samples/blob/master/01-Login/src/react-auth0-spa.js#L4-L5).

I can't find the sample you mentioned.

**Comment by Wynston** [comment]
A bunch of our users are hitting a similar error at `src/Auth0Client.ts:467`. 70% of these errors occur from iOS 12.1.2 but thats probably more related to our userbase than the bug.

```
// Transaction should have a `code_verifier` to do PKCE and a `nonce` for CSRF protection
if (!transaction || !transaction.code_verifier || !transaction.nonce) {
    throw new Error('Invalid state');
}
```

**Comment by jleppert** [comment]
Just want to add my feedback that our previously working auth (no changes on our side) all of a sudden starting breaking on Android Chrome with this error. Incredibly difficult to debug!

Also, what's with closing an issue when you clearly haven't resolved it? It seems like the general quality of Auth0 has declined greatly in the past few months.

**Comment by stevehobbsdev** [comment]
@jleppert The sample has moved on greatly since the issue was first raised and now uses auth0-react, whereas previously it did its own thing.

If you're still having trouble with this, I'd be happy to look at a repro if you can provide one.

> what's with closing an issue when you clearly haven't resolved it?

Because we weren't able to reproduce it and no-one was able to provide a sample to us that demonstrated the failure.

**Comment by ajmeraaxesh** [comment]
I am seeing an intermittent issue of "Invalid-State" with my Next's Static Apps which uses auth0-react-sdk.

This is my setup

```
const onRedirectCallback = appState => {
  console.log('OnRedirectCallback() => ', {appState})
  Router.replace(appState?.returnTo || `${window.location.origin}${TESTINDEX}`)
}

function MyApp({Component, pageProps}) {
  return (
    <Auth0Provider
      domain={process.env.NEXT_PUBLIC_AUTH0_DOMAIN}
      clientId={process.env.NEXT_PUBLIC_CLIENT_ID}
      audience={process.env.NEXT_PUBLIC_AUTH0_AUDIENCE}
      redirectUri={
        typeof window !== 'undefined' && `${window.location.origin}${TESTINDEX}`
      }
      onRedirectCallback={onRedirectCallback}
      useRefreshTokens
    >
      <Head>
        <meta name="viewport" content="width=device-width" />
        <meta charSet="utf-8" />
        <link rel="icon" type="image/png" href="/images/favicon.ico" />
      </Head>

      <Component {...pageProps} />
    </Auth0Provider>
  )
}
```

Please suggest what needs to be done to avoid this issue

**Comment by jbbch** [comment]
I'm having the same issue with next.js and auth0-react-sdk libraries as @ajmeraaxesh 
Were you able to resolve that somehow?
