### ISSUE TITLE
[Bug?] Login does not survive page refresh

### ISSUE THREAD

**Issue by benallfree** [auth0-samples/auth0-react-samples#190]
I just tried the `01-Login` sample and noticed that it does not stay logged in when I refresh the page. It seems that this is a bug, correct? It is also happening in my other projects. Is it related to the `SameSite` warning?

![2020-03-21_17-19-49 (1)](https://user-images.githubusercontent.com/1068356/77239498-bee37480-6b98-11ea-852c-4dae83fb754e.gif)

**Comment by stevehobbsdev** [comment]
@benallfree I'm 90% sure this is because you are using the classic login screen (Lock) with Google, but you are using Auth0's development keys with the Google social connection. In this scenario, silent authentication does not work and you appear logged out when you refresh.

Therefore, can you:

* Check whether you are indeed using Auth0's development keys for your Google social connection?
* Verify that if you log in using username/password, you are able to refresh the page and stay logged in?

Regarding the SameSite warning, you will getting this from the legacy cookie that we set for older browsers that do not support the SameSite attribute. However, if you inspect the network transactions you should find that the `auth0` cookie has the SameSite attribute set correctly to 'None'.

**Comment by benallfree** [comment]
@stevehobbsdev Thank you for offering some help. When you say classic login screen, do you mean there is another one to use instead? 

I disabled Google, and now it's just down to a login/pw screen.

But I'm getting a consent prompt, which I did not expect - is this part of the end user experience?

![image](https://user-images.githubusercontent.com/1068356/77333205-4c7dac00-6ce0-11ea-9650-2157392bc791.png)

(PS - if I try to sign up with an existing email address, it just says signup failed but doesn't say why)

**Comment by stevehobbsdev** [comment]
> When you say classic login screen, do you mean there is another one to use instead?

Yes - you can choose between Classic and New. From the screenshot I can see you're using the classic one. If you head to your Auth0 Dashboard > Univeral Login menu you will be able to choose between the two. Which one you use depends on your needs. "New" is more modern offers very few customization options (but will fix your issue). "Classic" is very customizable but has some niggles.

> But I'm getting a consent prompt, which I did not expect - is this part of the end user experience?

If you're signing up as a new user or connecting to an app for the first time as an existing user, you will see this consent screen that asks you to confirm access to your profile and email (plus other scopes if you have them). Consequent logins will not usually show this screen but may do if you add more scopes later.
>  if I try to sign up with an existing email address, it just says signup failed but doesn't say why

Can you show me the screen you're seeing? It's probably failing if you're signing up with an existing user, but it should tell you that.

**Comment by benallfree** [comment]
> If you're signing up as a new user or connecting to an app for the first time as an existing user, you will see this consent screen that asks you to confirm access to your profile and email

That makes sense for a social login, but for a username/password login too? I assumed that would behave just like a normal native account login on any other site.

In any case, I tried creating a new account. But it landed here, unfortunately with no explanation:

![image](https://user-images.githubusercontent.com/1068356/77334845-910a4700-6ce2-11ea-812b-89d9f0af6fcf.png)

I looked in the Auth0 dashboard and the user was created. When I try logging in again, it does the same thing.

**Comment by benallfree** [comment]
Sorry `Unable to issue redirect for OAuth 2.0 transaction` is the error

**Comment by stevehobbsdev** [comment]
Are you setting `redirect_uri` when you create the `Auth0Client`? Are you using the React Hooks wrapper found in this sample?

I see you have the error reason now - you can also click "See details for this error" on that error page to see more details about the failure.

> That makes sense for a social login, but for a username/password login too? I assumed that would behave just like a normal native account login on any other site.

Not sure about this - let me find out.

**Comment by stevehobbsdev** [comment]
Also, are you running this app on `localhost` or have you deployed it somewhere?

**Comment by benallfree** [comment]
Working now. And survives a refresh. So I think there were a couple problems in my case:

1. I had Google SSO enabled, but not configured with my own keys. 
2. I was using the Classic auth0 login UI, which you said doesn't play well Auth0's default developer oAuth keys in Google
3. I had the `redirect_uri` misconfigured so it wasn't redirecting...even though, weirdly, it was fine without it when I was using Google provider :)

Thank you, and my apologies that this turned into more of a support request and less of a developer issue.

**Comment by stevehobbsdev** [comment]
No problem! Glad you got it sorted :)

**Comment by clehene** [comment]
@stevehobbsdev the same thing happens on LinkedIn

To be clear - is there any way classic login survives a page refresh? If not, it should be a bug?

**Comment by stevehobbsdev** [comment]
> is there any way classic login survives a page refresh?

Not when using the default development keys in your social providers , no. You must supply real API keys for most social providers rather than using Auth0's development keys (including LinkedIn). You can also login with a username and password, which keeps the session.

[They're limited for testing purposes only](https://auth0.com/docs/connections/social/devkeys) and should not be used in production.
