### ISSUE TITLE
Need to remove cache? after refreshing the page

### ISSUE THREAD

**Issue by Abdul-majid-ashrafi** [auth0-samples/auth0-react-samples#205]
Hello,
I am following this documentation [https://auth0.com/docs/quickstart/spa/react](url)
but when doing refresh a page it is unable to reload the resources..
So we need to remove the cache from browser and then re-login..
please let me know what happening? and how to solve?

**Comment by stevehobbsdev** [comment]
Hi @Abdul-majid-ashrafi,

I have a few questions which might help me fix your issue:

* What exactly is happening when you refresh a page? What do you mean by "unable to reload the resources"?
* Can you provide screenshots?
* Can you provide a sample application that reproduces the issue?

Thanks!

**Comment by drewstone** [comment]
The page gets stuck with the loading gif afaik. I'm experiencing the same after logging in and trying to use the site while developing.

**Comment by newrol** [comment]
I had a similar issue when I tried sample-01.

I'm using the Linkedin auth method, and I have configured the application URIs to localhost(redirect, Cors, origin, log out...)

I can go through the login/logout process as expected. The problem appears when I'm logged in and I try to open a new tab with the webApp, reload the current tab, or try to open a new nav window with de app. 

I get this unauthorised message:
<img width="694" alt="Screenshot 2020-08-14 at 13 43 17" src="https://user-images.githubusercontent.com/11231994/90247015-08797800-de36-11ea-9e0d-468f5560b600.png">

<img width="552" alt="Screenshot 2020-08-14 at 13 55 38" src="https://user-images.githubusercontent.com/11231994/90246921-db2cca00-de35-11ea-8e8a-f728b5dfc8ac.png">

This cookie message:

<img width="770" alt="Screenshot 2020-08-14 at 13 43 05" src="https://user-images.githubusercontent.com/11231994/90246449-f3e8b000-de34-11ea-9c8b-b90d29f22d04.png">

And the non finish loading window:

<img width="339" alt="Screenshot 2020-08-14 at 13 43 28" src="https://user-images.githubusercontent.com/11231994/90246453-f64b0a00-de34-11ea-8787-31de44bfd053.png">


In order to continue working I have to change "auth0.is.authenticated" cookie value to false, reload the page, and press login button.

**Comment by newrol** [comment]
> I had a similar issue when I tried sample-01.
> 
> I'm using the Linkedin auth method, and I have configured the application URIs to localhost(redirect, Cors, origin, log out...)
> 
> I can go through the login/logout process as expected. The problem appears when I'm logged in and I try to open a new tab with the webApp, reload the current tab, or try to open a new nav window with de app.
> 
> I get this unauthorised message:
> <img alt="Screenshot 2020-08-14 at 13 43 17" width="694" src="https://user-images.githubusercontent.com/11231994/90247015-08797800-de36-11ea-9e0d-468f5560b600.png">
> 
> <img alt="Screenshot 2020-08-14 at 13 55 38" width="552" src="https://user-images.githubusercontent.com/11231994/90246921-db2cca00-de35-11ea-8e8a-f728b5dfc8ac.png">
> 
> This cookie message:
> 
> <img alt="Screenshot 2020-08-14 at 13 43 05" width="770" src="https://user-images.githubusercontent.com/11231994/90246449-f3e8b000-de34-11ea-9c8b-b90d29f22d04.png">
> 
> And the non finish loading window:
> 
> <img alt="Screenshot 2020-08-14 at 13 43 28" width="339" src="https://user-images.githubusercontent.com/11231994/90246453-f64b0a00-de34-11ea-8787-31de44bfd053.png">
> 
> In order to continue working I have to change "auth0.is.authenticated" cookie value to false, reload the page, and press login button.


I apologize, it was a wrong config setup 😅😅

**Comment by devanshjain14** [comment]
> > I had a similar issue when I tried sample-01.
> > I'm using the Linkedin auth method, and I have configured the application URIs to localhost(redirect, Cors, origin, log out...)
> > I can go through the login/logout process as expected. The problem appears when I'm logged in and I try to open a new tab with the webApp, reload the current tab, or try to open a new nav window with de app.
> > I get this unauthorised message:
> > <img alt="Screenshot 2020-08-14 at 13 43 17" width="694" src="https://user-images.githubusercontent.com/11231994/90247015-08797800-de36-11ea-9e0d-468f5560b600.png">
> > <img alt="Screenshot 2020-08-14 at 13 55 38" width="552" src="https://user-images.githubusercontent.com/11231994/90246921-db2cca00-de35-11ea-8e8a-f728b5dfc8ac.png">
> > This cookie message:
> > <img alt="Screenshot 2020-08-14 at 13 43 05" width="770" src="https://user-images.githubusercontent.com/11231994/90246449-f3e8b000-de34-11ea-9c8b-b90d29f22d04.png">
> > And the non finish loading window:
> > <img alt="Screenshot 2020-08-14 at 13 43 28" width="339" src="https://user-images.githubusercontent.com/11231994/90246453-f64b0a00-de34-11ea-8787-31de44bfd053.png">
> > In order to continue working I have to change "auth0.is.authenticated" cookie value to false, reload the page, and press login button.
> 
> I apologize, it was a wrong config setup 😅😅

What was that you changed on your config setup? Can you please let me know as I have recently run into the same issue. TIA

**Comment by stevehobbsdev** [comment]
@devanshjain14 This is mostly likely down to your Allowed Web Origins config for the application in your Auth0 Dashboard. Please make sure it contains a value that relates to the origin that your app is running on.
