### ISSUE TITLE
Google account picture request forbidden

### ISSUE THREAD

**Issue by konradsopala** [auth0-samples/auth0-react-samples#221]
Hey there team!

Opening that issue on behalf of 5 users that reported such issue in our Auth0 Community Forum.

Context:

"I noticed that sometimes after I logged in with my Google account, the request to my profile picture returns a 403. After some time, the request returns the profile picture like normal."

"Logging in with google, everything seems to work fine and then suddenly after switching between views, the picture GET request returns a 403. A couple of hours later it works again, but the issue always comes back."

**Reference**: https://community.auth0.com/t/google-account-picture-request-forbidden/42031

**Comment by frederikprijck** [comment]
Hi @konradsopala,

This appears to happen for a few years outside of Auth0 context as well: https://stackoverflow.com/questions/40570117/http403-forbidden-error-when-trying-to-load-img-src-with-google-profile-pic

Based on the activity on StackOverflow, it looks like it only happens, randomly, if serving trough localhost. Can this be verified if the users also experience this when using `127.0.0.1` instead of localhost?

I havent been able to reproduce this, I tried refreshing with clearing the cache for +30 times.

**Comment by skipjack** [comment]
Interesting, yea at least for me switching from `localhost` to `127.0.0.1` seems to have immediately fixed the issue. Looking at that stack overflow post for more details.

**Comment by khandaniel** [comment]
From the question @frederikprijck has posted here: you have to add `<img src="" referrerpolicy="no-referrer" />`
