### ISSUE TITLE
Example for User Initiated Account Linking using this library

### ISSUE THREAD

**Issue by beem812** [auth0-samples/auth0-react-samples#232]
Hi, is there a way to manage user initiated account linking with this library? Or am I forced to use the auth0-spa-js library to accomplish that task? If it is possible could there be an example/sample created showing how that is done?

**Comment by stevehobbsdev** [comment]
Hi @beem812,

This repo is just a sample rather than something you can install as a library. `auth0-spa-js` also does not have any capability to use the management API to do account linking. Your options here are to use [`auth0.js`](https://github.com/auth0/auth0.js) (you can [read more about account linking in the docs](https://auth0.com/docs/libraries/auth0js#linking-users)) or use a back-end SDK to use the Auth0 API directly.

Hopefully the doc I provided gets you started, but happy to continue chatting if not.

**Comment by beem812** [comment]
No, knowing what the expected path is is good enough for me, thanks!
