### ISSUE TITLE
 Auth0-react failing silently on succesful login

### ISSUE THREAD

**Issue by sammbeller** [auth0-samples/auth0-react-samples#341]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-react-samples/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description
As requested in [this community forum post](https://community.auth0.com/t/auth0-react-failing-silently-on-succesful-login/109142/3), `auth0-react` is failing silently on login.
> Clicking the login button succeeds - I can see Success Login events in my user’s history. But the Auth0Provider’s reducer still has `isAuthenticated` set to false and no user populated.

### Reproduction
My `Auth0ProviderWithHistory` is as follows:
```ts
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Auth0Provider, Auth0ProviderOptions } from '@auth0/auth0-react';

type Auth0ProviderWithHistoryProps = React.PropsWithChildren<{}>;

const Auth0ProviderWithHistory = (props: Auth0ProviderWithHistoryProps) => {
  const domain = process.env.REACT_APP_AUTH0_DOMAIN;
  if (!domain) {
    throw new Error("Could not get auth domain from env");
  }
  const clientId = process.env.REACT_APP_AUTH0_CLIENT_ID;
  if (!clientId) {
    throw new Error("Could not get auth client ID from env");
  }

  const navigate = useNavigate();

  const onRedirectCallback: Auth0ProviderOptions["onRedirectCallback"] = (appState) => {
    navigate(appState?.returnTo || window.location.pathname);
  };

  return (
    <Auth0Provider
      authorizationParams={{ redirect_uri: window.location.origin }}
      clientId={clientId}
      domain={domain}
      onRedirectCallback={onRedirectCallback}
    >
      {props.children}
    </Auth0Provider>
  );
};

export default Auth0ProviderWithHistory;
```
Login is implemented as described in the login tutorial [here](https://auth0.com/docs/quickstart/spa/react/01-login). Login fails every time as described above.

### Environment
- **Version of this library used:** `@auth0/auth0-react: ~2.0.2`
- **Version of the platform or framework used, if applicable:** `react: ^17.0.2`
- **Other relevant versions (language, server software, OS, browser):** 
  - node: v16.18.0
- **Other modules/plugins/libraries that might be involved:** none that I can think of

### Which browsers have you tested in?

Firefox

**Comment by frederikprijck** [comment]
Thanks for reporting and sorry for the delayed response.

While I look into this, I wanted to see if you have third-party cookies blocked or not?

**Comment by frederikprijck** [comment]
I tested this by doing the following:

- Upgrade the sample application to use React Router v6
- Use the `Auth0ProviderWithHistory` provided

Once I login, and come back to the application, I am successfully logged in in both Chrome and Firefox and can see my user information and authenticated state.

Could you share a reproducible project to look into to try and identify what's causing it?

**Comment by jburos** [comment]
I ran into a similar problem which was due to my getting a 401/Unauthorized error on getting the authorization token via /oauth/token, similar in behavior to this old [bug report](https://community.auth0.com/t/401-unauthorized-when-obtaining-token-in-authorization-code-grant/44685/19).

Following the logic of that report, I tried setting the Authentication Method to "None" under the "Credentials" tab of my application settings. This resolved the error, for me at least. 

This is an area that could use more documentation/clarification in the example, since the default application includes a secret but the docs aren't clear on how to pass that to the auth0 provider.

**Comment by frederikprijck** [comment]
Thanks, the example in this repo is for the [quickstart](https://auth0.com/docs/quickstart/spa/react), as you can see in the repo's readme.

That quickstart calls out the need for setting it to none.

Our react SDK does not, and should not, accept a secret so there is no way to pass one because this is for public clients only (clients that are public should not contain a secret as they would expose it and it no longer is a "secret").
