### ISSUE TITLE
Can't resolve 'history/createBrowserHistory'

### ISSUE THREAD

**Issue by tiagostutz** [auth0-samples/auth0-react-samples#35]
Hi. When trying to run th **01-Login example** I had issues with the history.js file. The error received was:

`Can't resolve 'history/createBrowserHistory'`

To solve that, I had to add the `history` dependency to my package.json dependencies: `"history": "^4.6.3"`

I don't know whether this dependency was supposed to be installed as a automatic dependency of Router4 or if this is was a bug. Any thoughts?

**Comment by colemannerd** [comment]
They're using the history object that is silently installed when you instal react-router-dom.  If you add it as a package, it will break.  I really do not like this solution because it breaks the declarative routing that react-router-v4 wants you to use.  I have not found a way that works to do this.

**Comment by williamsb** [comment]
If you look for the history package in node_modules you can see the path for 'createBrowserHistory' which was 'history/lib/createBrowserHistory' for me.

**Comment by luisrudge** [comment]
I believe this is now working as expected. I just tried the sample 01 and it works. Let me know if you need more help! 🎉
