### ISSUE TITLE
Embeddes Login example does not work; returns 403

### ISSUE THREAD

**Issue by saschajullmann** [auth0-samples/auth0-react-samples#41]
Hi guys,

I was just trying to get the auth0-lock to work within my react application but have failed to do so (btw. I'm only trying to use the lock-widget since using the hosted login pages does currently not work with Safari/Safari mobile, but that's a different topic.)

Steps to reproduce:

Clone the repo with the Embedded Login Code.
Install the dependencies.
Create a new Client in the auth0 dashboard (since you didn't specify I used a "Single Page App Client").
Copy the client-id and the domain into "auth0-variables.js".
Start the application with "yarn start".
Click on Login and enter credentials with a user that was added manually via dashboard.
An error will be returned: POST https://YOUR_DOMAIN/oauth/token 403 ()

I really need to get this to work. Did anybody else get this to work? If not, is there any direction someone could point me to for a setup with auth0 where Safari will be supported?

EDIT: It seems that passing the option "oidcConformant: true" to the Auth0Lock is the problem. If I leave that out (and thereby also have to leave out the audience) I can successfully authenticate. I will go with that for now.

**Comment by eggsy84** [comment]
I think this is because new clients no longer have the Password 'Grant type' 

https://auth0.com/docs/clients/client-grant-types

I'm still struggling to understand what implications this has when enabling it on things like a public facing SPA. They recommend that it is not enabled but if you've worked with legacy Auth0 clients then it seems to be enabled by default.

It would be nice to see the embedded branch be updated with instructions based upon the new client setup

**Comment by luisrudge** [comment]
we're now using the hosted login page, so different grant types are not an issue anymore 🎉
