### ISSUE TITLE
Dynamically refreshing the login state

### ISSUE THREAD

**Issue by SachaG** [auth0-samples/auth0-react-samples#72]
In the Lock examples, the page is refreshed once the user logs in because of the route change. But how could you achieve the same result *without* changing the route, i.e. by changing the state of the parent React component?

**Comment by jimmyjames** [comment]
Closing this issue  since we've just recently made some significant changes to this sample and Quickstart, utilizing the new `auth0-spa-js` SDK. If you continue to experience this issue or any others, don't hesitate to create a new issue. Thanks!

References:
- [Updated React Quickstart](https://auth0.com/docs/quickstart/spa/react)
- [auth0-spa-js SDK](https://github.com/auth0/auth0-spa-js)
